name: Test & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          lfs: true
      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Run build
        run: yarn build
      - name: Netlify deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=out_publish --functions=out_functions
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
