name: Test

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test
      - name: Run E2E tests
        uses: cypress-io/github-action@master
        with:
          record: false
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:3000'
